SOURCES = EngineManager.cpp Geometry.cpp Main.cpp Model.cpp \
	  Shaders.cpp TGAImage.cpp 

HEADERS = EngineManager.h Geometry.h Line.h Model.h Shaders.h \
	  TGAImage.h Triangle.h

TinyRender.out : $(HEADERS) $(SOURCES)
	g++ $(SOURCES)
